blog/urls.py
from django.urls import path
from .views import*

urlpatterns = [
    path('', HomeView.as_view()),
    path('<int:id>/', BlogDetail.as_view()),
    path('search/', SearchView.as_view()),
]

server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('user/', include('user.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from user.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 116)
    content = models.TextField()
    image = models.ImageField(upload_to = 'blog')
    date = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add = True)

shop/models.py
from django.db import models
from user.models import User

drinkChoices = [
    ('0', 'lạnh'),
    ('1', 'nóng'),
]

sizeChoices = [
    ('0', 'M'),
    ('1', 'L'),
]

sugarChoices = [
    ('0', '70%'),
    ('1', '30%'),
    ('2', '100%'),
    ('3', '50%'),
    ('4', 'Không đường'),
]

toppingChoices = [
    ('0', 'Trân trâu sương mai'),
    ('1', 'Trân châu hoàng kim'),
    ('2', 'Thạch Konjac'),
    ('3', 'Thạch cafe'),
    ('4', 'Thạch Machiato'),
]

# Create your models here.
class Product(models.Model):
    image = models.ImageField(null = True, blank = True, upload_to="product")
    name = models.CharField(max_length = 116)
    price = models.IntegerField(default = 0)

    def __str__(self):
        return self.name
    
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    drinkType = models.CharField(default = 0, choices = drinkChoices)
    sizeType = models.CharField(default = 0, choices = sizeChoices)
    sugarType = models.CharField(default = 0, choices = sugarChoices)
    toppingType = models.CharField(default = 0, choices = toppingChoices)
    quantity = models.IntegerField(default = 0)
    price = models.IntegerField(default = 0)

    def __str__(self):
        return str(self.product.name) + '-' + str(self.id)
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    cartItem = models.ManyToManyField(CartItem)

    def __str__(self):
        return self.user.username

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    address = models.CharField(max_length = 116)
    phoneNumber = models.CharField(max_length = 116)
    cartItem = models.ManyToManyField(CartItem)
    price = models.IntegerField(default = 0)

blog/forms.py
from django import forms
from .models import*

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['content']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class': 'form-control'})

blog/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import*

# Create your views here.
class HomeView(View):
    def get(self, request):
        posts = Post.objects.all().order_by('-date')
        return render(request, 'pages/blog.html', {
            'posts': posts,
        })

class BlogDetail(View):
    def get(self, request, id):
        post = Post.objects.get(id = id)
        comments = Comment.objects.filter(post = id).order_by('-date')
        form = CommentForm()
        recentPosts = Post.objects.all().order_by('-date')[0:3]
        return render(request, 'pages/blog_detail.html', {
            'post': post,
            'comments': comments,
            'form': form,
            'recentPosts': recentPosts,
        })
    
    def post(self, request, id):
        form = CommentForm(request.POST)
        post = Post.objects.get(id = id)
        form.instance.post = post
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return redirect('/blog/')
        return redirect('/')

class SearchView(View):
    def get(self, request):
        return render(request, 'pages/blog_search.html')
    
    def post(self, request):
        search = request.POST['search']
        posts = Post.objects.filter(title__contains = search)
        return render(request, 'pages/blog_search.html', {
            'search': search,
            'posts': posts,
        })

templates/pages/blog.html
{% extends 'components/base.html' %}

{% block title %}Blog{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in posts %}
        <div class="col">
            <a href="/blog/{{post.id}}/" style="text-decoration: none; color: black;">
                <div class="card h-100">
                    <img src="../../media/{{post.image}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{post.title}}</h5>
                        <p class="card-text">{{post.content}}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/pages/blog_detail.html
{% extends 'components/base.html' %}

{% block title %}{{post.title}}{% endblock %}

{% block content %}
<div class="container">
    <div class="text-center mx-auto">
        <h1>Blog</h1>
        <p>Chia sẻ giải pháp quản lý cửa hàng. Tương tác hai chiều, trao đổi, chia sẻ kinh nghiệm quản lý trong ngành bán lẻ của Tocotoco và các chủ cửa hàng</p>
    </div>
    <div class="row">
        <div class="col-lg col-md">
            <div class="m-3">
                <h4>{{post.title}}</h4>
                <p>{{post.subTitle|linebreaks}}</p>
                <img src="../../media/{{post.image}}" class="img-fluid" alt="..." width="650" style="border-radius: 1rem;">
                <p>{{post.content|linebreaks}}</p>
                <h3>Comment</h3>
                <button class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#add-comment" aria-expanded="false" aria-controls="add-c#add-comment">Thêm bình luận</button>
                <div class="collapse" id="add-comment">
                    <div class="card card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button class="btn btn-primary">Thêm bình luận</button>
                        </form>
                    </div>
                </div>
                {% for comment in comments %}
                    <div class="comment my-3 ps-2">
                        <h5>{{comment.user.username}}</h5>
                        <p>{{comment.content|linebreaks}}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg col-md">
            <div class="m-3">
                <form action="/blog/search/" method="POST" class="input-group">
                    {% csrf_token %}
                    <span class="input-group-text" id="addon-wrapping">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                        </svg>
                    </span>
                    <input type="text" class="form-control" placeholder="search..." name="search" id="search">
                </form>
                <div class="mt-3">
                    <img src="../../media/img/product-img.gif" alt="" class="img-fluid" width="500">
                </div>
                <div class="container-fluid">
                    <div style="background-color: black; text-align: center; color: white; padding: 6px;">
                        <h1>Bài viết gần đây</h1>
                    </div>
                    <div class="container-fluid">
                        {% for post in recentPosts %}
                            <a href="/blog/{{post.id}}/" style="text-decoration: none; color: black;">
                                <div class="card h-100 my-3">
                                    <img src="../../media/{{post.image}}" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">{{post.title}}</h5>
                                        <p class="card-content">{{post.subTitle}}</p>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/blog_search.html
{% extends 'components/base.html' %}

{% load humanize %}
{% block title %}Blog Search{% endblock %}

{% block content %}

<div class="container">
    <h1>You searched for {{search}}</h1>
    <div class="container mx-5 my-5">
        <div class="row row-cols-3 row-cols-md-3 g-4">
            {% for post in posts %}
                <a href="/blog/{{post.id}}/" style="text-decoration: none; color: black;">
                    <div class="col product">
                        <div class="card h-100">
                            <img src="../../media/{{post.image}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-content">{{post.subTitle}}</p>
                            </div>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/pages/cart.html
{% extends 'components/base.html' %}

{% load humanize %}
{% block title %}Cart{% endblock %}

{% block content %}

{% if user.username %}
    <div class="container my-3">
        <div class="row">
            <div class="col-lg col-md">
                <div class="payment my-3 p-3">
                    <h1 class="text-center">Thanh Toán</h1>
                    {% if cart.count %}
                        <a href="/remove-all-cart-item/" style="color: red; text-decoration: none;">xóa tất cả</a>
                        <p style="color: red; text-decoration: none;">Tổng số tiền phải trả là: {{cost|intcomma}}đ</p>
                        <form action="" method="post">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button class="btn btn-primary">CHECKOUT</button>
                        </form>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg col-md">
                {% for cartItem in cart %}
                    <div class="cart-item my-3 p-3">
                        <a href="/delete-cart-item/{{cartItem.id}}/" class="btn-close" aria-label="Close"></a>
                        <div>
                            <img src="../../media/{{cartItem.product.image}}" class="img-fluid" alt="" width="100" style="border-radius: 1rem;">
                        </div>
                        <h6>{{cartItem.product.name}}</h6>
                        <p>Loại đồ uống: {{cartItem.get_drinkType_display}}</p>
                        <p>Size: {{cartItem.get_sizeType_display}}</p>
                        <p>Phần trăm đường: {{cartItem.get_sugarType_display}}</p>
                        <p>Topping đi kèm: {{cartItem.get_toppingType_display}}</p>
                        <p>Giá 1 ly: <span style="color: red;">{{cartItem.product.price|intcomma}}đ</span></p>
                        <p>Số lượng đặt hàng: <span style="color: red;">{{cartItem.quantity}}</span></p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% else %}
    <h1>You must log in to use our sevices.</h1>
    <p><a href="/user/login/">Login</a> if you already have an account.</p>
    <p><a href="/user/register/">Register</a> if you don't have an account.</p>
{% endif %}

{% endblock %}

templates/pages/index.html
{% extends 'components/base.html' %}

{% load humanize %}
{% block title %}Home{% endblock %}

{% block content %}

<div id="carouselExampleCaptions" class="carousel slide">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://tocotocotea.com/wp-content/uploads/2022/06/Slide_banner-1-1.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1>ĐẶT HÀNG NGAY</h1>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://tocotocotea.com/wp-content/uploads/2022/06/Slide_banner-2.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1>ĐẶT HÀNG NGAY</h1>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://tocotocotea.com/wp-content/uploads/2022/06/Slide_banner-3.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h1>ĐẶT HÀNG NGAY</h1>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div class="container my-5">
    <div class="my-5">
        <form action="/search/" method="POST" class="input-group">
            {% csrf_token %}
            <span class="input-group-text" id="addon-wrapping">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
            </span>
            <input type="text" class="form-control" placeholder="search..." name="search" id="search">
        </form>
    </div>
    <div>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for product in products %}
                <div class="col product">
                    <div class="card h-100">
                        <img src="../../media/{{product.image}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{product.name}}</h5>
                            <p style="color: red;">{{product.price|intcomma}}đ</p>
                            <a href="/{{product.id}}/" class="btn">ORDER</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/pages/login.html
{% extends 'components/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-floating my-5">
            <input type="text" class="form-control" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="254" required="" id="id_username">
            <label for="id_username">Email</label>
        </div>
        <div class="form-floating my-5">
            <input type="password" class="form-control" name="password" autocomplete="current-password" required="" id="id_password">
            <label for="id_password">Password</label>
          </div>
        <input type="hidden" name="next" value="/"/>
        <button class="btn">ĐĂNG NHẬP</button>
    </form>
</div>

{% endblock %}

templates/pages/order.html
{% extends 'components/base.html' %}

{% load humanize %}
{% block title %}Order{% endblock %}

{% block content %}

{% if user.username %}
    <div class="container my-3">
        <div class="row">
            <div class="col-lg col-md">
                <img src="../../media/{{product.image}}" class="img-fluid" alt="" width="500" height="500">
            </div>
            <div class="col-lg col-md">
                <div>
                    <h1>{{product.name}}</h1>
                    <p style="color: red;">{{product.price|intcomma}}đ</p>
                </div>
                <div>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-primary">PURCHASE</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <h1>You must log in to use our sevices.</h1>
    <p><a href="/user/login/">Login</a> if you already have an account.</p>
    <p><a href="/user/register/">Register</a> if you don't have an account.</p>
{% endif %}

{% endblock %}

templates/pages/register.html
{% extends 'components/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}

<div class="container">
    <form action="" method="post" class="">
        {% csrf_token %}
        <div class="form-floating my-5">
            {{form.username}}
            <label>Username</label>
        </div>
        <div class="form-floating my-5">
            {{form.email}}
            <label>Email</label>
        </div>
        <div class="form-floating my-5">
            {{form.password1}}
            <label>Password</label>
        </div>
        <div class="form-floating my-5">
            {{form.password2}}
            <label>Password Confirm</label>
        </div>
        <button class="btn">ĐĂNG KÝ</button>
    </form>
</div>

{% endblock %}

templates/pages/search.html
{% extends 'components/base.html' %}

{% load humanize %}
{% block title %}Search{% endblock %}

{% block content %}

<div class="container">
    <h1>You searched for {{search}}</h1>
    <div class="row row-cols-3 row-cols-md-3 g-4">
        {% for product in products %}
            <div class="col product">
                <div class="card h-100">
                    <img src="../../media/{{product.image}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p style="color: red;">{{product.price|intcomma}}đ</p>
                        <button class="order-button btn">ORDER</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}